# Generated by Django 5.1.4 on 2024-12-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='file path'),
        ),
    ]
