# Generated by Django 5.1.4 on 2024-12-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='file_path',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='file path'),
        ),
    ]
