# Generated by Django 5.1.4 on 2024-12-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_created_filmwork_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
